### ISSUE TITLE
Delete All Applications in simulator

### ISSUE THREAD

**Issue by Vaberer** [tue-savvy/SimulatorManager#3]
Hello, I have just tried to Simulator Manager, and after pressing Reset All simulators, the applications installed in the simulator  were not deleted.

Am I doing something wrong or is it an issue?
Thanks

**Comment by tue-savvy** [comment]
Did you try to build & run the app on simulator after pressing Reset? I will try at my side, may be it is an issue when detecting installed applications.

**Comment by webdevbrian** [comment]
for the un-savvy - can you offer a .app that's already been compiled? I have a friend that needs this and I'm not on my mac to compile it for him.

**Comment by tue-savvy** [comment]
@webdevbrian You can download binary (pre-compiled version) from this link: https://github.com/tue-savvy/SimulatorManager/releases/tag/1.2.1
