### ISSUE TITLE
SimulatorManager does not reliably find all data folders

### ISSUE THREAD

**Issue by bunnyhero** [tue-savvy/SimulatorManager#4]
i have several apps whose app data folders cannot be found by SimulatorManager. however, they are successfully found by https://github.com/somegeekintn/SimDirs

**Comment by tue-savvy** [comment]
Let me take a look on the app. May be I will find something useful :)

**Comment by tue-savvy** [comment]
Thanks @bunnyhero. I updated the app already. Please try latest version :) https://github.com/tue-savvy/SimulatorManager/releases/tag/1.3

**Comment by bunnyhero** [comment]
awesome, it works! :+1: thank you :)
